name: Publish to GHCR.io

on:
  push:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
    - name: Get short SHA
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push images
      run: |
        cd python
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        docker buildx build --push -t $IMAGE_NAME:${{ env.SHORT_SHA }} .
